on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build-and-publish:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.repository == 'jni/skan'
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip install -e .  # need full install so we can build type stubs
      - name: Build Distribution
        run: python -m build
      - name: Publish PyPI Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.tag }}
          body_path: release-latest.md
          draft: ${{ contains(github.ref, 'rc') }}
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: ./dist/skan-${{ env.tag }}.tar.gz
